### ISSUE TITLE
Working problem.

### ISSUE THREAD

**Issue by 0xjohn** [360-A-Team/getpass#1]
Hi,

I compiled getpass and try to test it, but I got an error.

> Token AuthenticationId:0 62709679
[*] Enable debug privilege
[*] Open process lsass.exe
Open lsass.exe successfully, PID=552
[*] Dump 3deskey and iv
Module ulVersion: 6000325804ac3
File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
Cant find h3deskey pointer, maybe unsupport this version
[*] Dump wdigest password entries
Module ulVersion: 600032580479e
File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
cant find wdigest!l_LogSessList
[*] Dump msv1_0 hash entries
Module ulVersion: 6000325804ac3
File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
Cant find lsasrv!logonSessList
[*] Dump tspkg password entries
Module ulVersion: 6000325804a37
File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
Cant find tspkg!TSGlobalCredTable

I tested it on Win10 x64 and Win2012 x64 but always got this error.
Where is the problem?

@Feb30th @Luanana @n1nty @Tycx2ry

**Comment by Feb30th** [comment]
> Hi,
> 
> I compiled getpass and try to test it, but I got an error.
> 
> > Token AuthenticationId:0 62709679
> > [_] Enable debug privilege
> > [_] Open process lsass.exe
> > Open lsass.exe successfully, PID=552
> > [_] Dump 3deskey and iv
> > Module ulVersion: 6000325804ac3
> > File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
> > Cant find h3deskey pointer, maybe unsupport this version
> > [_] Dump wdigest password entries
> > Module ulVersion: 600032580479e
> > File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
> > cant find wdigest!l_LogSessList
> > [_] Dump msv1_0 hash entries
> > Module ulVersion: 6000325804ac3
> > File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
> > Cant find lsasrv!logonSessList
> > [_] Dump tspkg password entries
> > Module ulVersion: 6000325804a37
> > File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
> > Cant find tspkg!TSGlobalCredTable
> 
> I tested it on Win10 x64 and Win2012 x64 but always got this error.
> Where is the problem?
> 
> @Feb30th @Luanana @n1nty @Tycx2ry

This project is a demo. so my pattern is write in hard code.

**Comment by 0xjohn** [comment]
thanks, so how can I change it to work in my own?

**Comment by Feb30th** [comment]
> thanks, so how can I change it to work in my own?

In fact, mimikatz work with hard code also, but it collected all of windows versions. So you must check out the hard code works for you. -_-

**Comment by 0xjohn** [comment]
I check your source code and find the pattern section, I tested on win10x64 1803 and win10x64 1709.
I got an error on both versions too.

win10x64 1709 result...

> Token AuthenticationId:0 2599462
[*] Enable debug privilege
[*] Open process lsass.exe
Open lsass.exe successfully, PID=612
[*] Dump 3deskey and iv
Module ulVersion: a00003fab000f
File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
Cant find h3deskey pointer, maybe unsupport this version
[*] Dump wdigest password entries
Module ulVersion: a00003fab000f
wdigest!l_LogSessList in lsass 0x00007FFB5A184DA0
Administrator\Administrator ():[]
admin\ADMIN2C08 ():[]
admin\ADMIN2C08 ():[]
ADMIN2C08$\WORKGROUP ():[]
ADMIN2C08$\WORKGROUP ():[]
ADMIN2C08$\WORKGROUP ():[]
ADMIN2C08$\WORKGROUP ():[]
\ ():[]
ADMIN2C08$\WORKGROUP ():[]
ADMIN2C08$\WORKGROUP ():[]
[*] Dump msv1_0 hash entries
Module ulVersion: a00003fab000f
File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
Cant find lsasrv!logonSessList
[*] Dump tspkg password entries
Module ulVersion: a00003fab000f
File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
Cant find tspkg!TSGlobalCredTable

**Comment by Feb30th** [comment]
> I check your source code and find the pattern section, I tested on win10x64 1803 and win10x64 1709.
> I got an error on both versions too.
> 
> win10x64 1709 result...
> 
> > Token AuthenticationId:0 2599462
> > [_] Enable debug privilege
> > [_] Open process lsass.exe
> > Open lsass.exe successfully, PID=612
> > [_] Dump 3deskey and iv
> > Module ulVersion: a00003fab000f
> > File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
> > Cant find h3deskey pointer, maybe unsupport this version
> > [_] Dump wdigest password entries
> > Module ulVersion: a00003fab000f
> > wdigest!l_LogSessList in lsass 0x00007FFB5A184DA0
> > Administrator\Administrator ():[]
> > admin\ADMIN2C08 ():[]
> > admin\ADMIN2C08 ():[]
> > ADMIN2C08$\WORKGROUP ():[]
> > ADMIN2C08$\WORKGROUP ():[]
> > ADMIN2C08$\WORKGROUP ():[]
> > ADMIN2C08$\WORKGROUP ():[]
> > \ ():[]
> > ADMIN2C08$\WORKGROUP ():[]
> > ADMIN2C08$\WORKGROUP ():[]
> > [_] Dump msv1_0 hash entries
> > Module ulVersion: a00003fab000f
> > File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
> > Cant find lsasrv!logonSessList
> > [_] Dump tspkg password entries
> > Module ulVersion: a00003fab000f
> > File:process.cpp Line:198 Function:FindPatternFromModule Api:MatchPattern Code:0
> > Cant find tspkg!TSGlobalCredTable

Notice that "Module ulVersion: a00003fab000f", I chose hardcode based on file version, maybe there's differences from your system. You can use IDA to find it, good luck!
